services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    ports:
      - "9092:9092"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  app-producer:
    build: .
    depends_on:
      - redpanda
    environment:
      - ROLE=producer
      - KAFKA_BROKER=redpanda:29092

  app-consumer:
    build: .
    depends_on:
      - redpanda
      - mongodb
    environment:
      - ROLE=consumer
      - KAFKA_BROKER=redpanda:29092
      - MONGODB_URI=mongodb://mongodb:27017
